---
- name: Restart networking
  command: systemctl restart networking

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Zmap
  apt:
    name: zmap
    state: present

- name: Copy nscan to /opt and make it executable
  ansible.builtin.copy:
    src: nscan
    dest: /opt
    mode: u+x,g+x,o+x
    owner: root
    group: root

echo "" > /etc/zmap/zmap.conf
sudo ip addr flush dev eth0

- name: Copy tests.sh to /opt and make it executable
  ansible.builtin.copy:
    src: tests.sh
    dest: /opt
    mode: u+x,g+x,o+x
    owner: root
    group: root

- ansible.builtin.include_tasks: openvas.yml
  when: include_openvas | bool