---
- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted
    
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Zmap
  apt:
    name: zmap
    state: present

- name: Download Go binary
  get_url:
    url: https://golang.org/dl/go1.23.1.linux-amd64.tar.gz
    dest: /tmp/go1.23.1.linux-amd64.tar.gz

- name: Extract Go binary
  unarchive:
    src: /tmp/go1.23.1.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Remove Go tar file
  file:
    path: /tmp/go1.23.1.linux-amd64.tar.gz
    state: absent

- name: Set up Go environment variable
  lineinfile:
    path: /etc/profile.d/golang.sh
    line: 'export PATH=$PATH:/usr/local/go/bin'
    create: yes
    state: present

- name: Copy nscan to /vagrant/home
  ansible.builtin.copy:
    src: nscan 
    dest: /opt

- ansible.builtin.include_tasks: openvas.yml
  when: include_openvas | bool