---
- name: Install Telnet and xinetd
  apt:
    name:
      - telnetd
      - xinetd
    state: present
    update_cache: yes

- name: Create xinetd configuration for Telnet (CVE-2016-5696)
  copy:
    dest: /etc/xinetd.d/telnet
    content: |
      service telnet
      {
          disable         = no
          flags           = REUSE
          socket_type     = stream
          wait            = no
          user            = root
          server          = /usr/sbin/in.telnetd
          log_on_failure  += USERID
          log_on_success  += PID HOST EXIT
          only_from       = 0.0.0.0/0
          port            = {{ telnet_port }}
      }

- name: Ensure Telnet service is listening on the custom port
  lineinfile:
    path: /etc/services
    regexp: '^telnet'
    line: "telnet   {{ telnet_port }}/tcp"
    state: present

- name: Restart xinetd
  service:
    name: xinetd
    state: restarted
