---
- name: Setup Web Server
  hosts: server0
  become: yes
  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: smtp-stop

- name: Setup File Server
  hosts: server1
  become: yes
  roles:
    - role: ftp
    - role: smb
    - role: smtp-stop

- name: Setup Telnet/SNMP Server
  hosts: server2
  become: yes
  roles:
    - role: snmp

- name: Enable UFW and setup Routing 
  hosts: servers
  become: yes
  roles:
    - role: ufw

- name: Execute kali role
  hosts: kali
  become: yes
  roles: 
    - role: kali

- name: Release and renew DHCP lease for eth1
  hosts: all
  become: yes
  roles:
    - role: networking