---
- name: Release DHCP lease on eth1
  ansible.builtin.command:
    cmd: dhclient -r eth1
  ignore_errors: yes

- name: Renew DHCP lease on eth1
  ansible.builtin.command:
    cmd: dhclient eth1

- name: Release DHCP lease on eth1 (again)
  ansible.builtin.command:
    cmd: dhclient -r eth1
  ignore_errors: yes

- name: Renew DHCP lease on eth1 (again)
  ansible.builtin.command:
    cmd: dhclient eth1
