---
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Enable specified ports in UFW
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ ports }}"

- name: Enable UFW
  ufw:
    state: enabled

- name: Ensure UFW is enabled on boot
  systemd:
    name: ufw
    enabled: yes

- name: Add route to 10.20.0.0/16 via 10.10.0.1
  command: ip route add 10.20.0.0/16 via 10.10.0.1